name: 'WordPress CI'
description: 'WordPress Plugin or Theme CI environment'
author: 'Impressible'
inputs:
  # Input(s) for getting the WordPress CI container image
  image:
    description: 'The container image to use'
    required: false
    default: 'ghcr.io/impressible-wp/wordpress-ci:latest'

  # Input(s) for configuring the WordPress CI container
  # before starting it
  network:
    description: 'The Docker network to use. Must match that of the database container.'
    required: false
    default: ''
  plugins:
    description: 'List of directories of plugins to test, one per line'
    required: false
    default: ''
  themes:
    description: 'List of directories of themes to test, one per line'
    required: false
    default: ''

  # Input(s) for the installation of WordPress in the container
  db-host:
    description: 'The hostname of the MySQL/MariaDB service container'
    required: false
    default: 'mysql'
  db-name:
    description: 'The name of the database to use'
    required: false
    default: 'wordpress'
  db-user:
    description: 'The database user to connect as'
    required: false
    default: 'username'
  db-password:
    description: 'The password for the database user'
    required: false
    default: 'password'

  # Input to control whether to clean the installation on start
  clean-on-start:
    description: 'Whether to clean the WordPress installation on start'
    required: false
    default: 'true'

  # Input(s) for importing database dumps
  import-sql:
    description: 'Path to an SQL file to import into the database. Please note that setting this would negate the unattained installation of WordPress.'
    required: false
    default: ''

  # Input(s) for running tests
  test-command:
    description: 'Command to use to run tests'
    required: true
    default: 'echo "No test command specified"'
  test-command-context:
    description: 'Directory to run the test command in'
    required: false
    default: '.'
outputs:
  stdout:
    description: 'The standard output of the action'
  stderr:
    description: 'The standard error output of the action'
  time:
    description: 'The time the action was run'
runs:
  using: 'node20'
  main: 'dist/index.js'
