name: 'Wordpress CI'
description: 'Wordpress Plugin or Theme CI environment'
author: 'Impressible'
inputs:
  workdir:
    description: 'Working directory'
    required: false
    default: '.'
  test-command:
    description: 'Command to use to run tests'
    required: true
    default: 'echo "No test command specified"'
runs:
  using: 'node20'
  main: 'dist/index.js'
