version: '3.8'

services:
  wp-plugin-ci:
    build:
      image: wp-plugin-ci:${PHP_VERSION:-8.1}
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.1}
    container_name: wp-plugin-ci
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - .:/myplugin
    ports:
      - "8080:80"
    networks:
      - network

  db:
    image: mariadb:latest
    container_name: wp-plugin-ci-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    networks:
      - network

networks:
  network:
    driver: bridge
